Mark discriminator properties of oneOf types mandatory.
fa0311/twitter-openapi pull request #12
Opened 2023-07-02 17:38 UTC by nevkontakte

Since they are used as a discriminator, it doesn't make sense for the field to be required and they do seem to be always present in practice. This also sidesteps a bug in https://github.com/deepmap/oapi-codegen, which generates invalid code if the field is optional.

2023-07-03 01:45 UTC, fa0311 commented
> it doesn't make sense for the field to be required and they do seem to be always present in practice.

Is this defined in the Swagger specification?

These identifier properties must allow null.

You can also add `tools/build_config.py` for third party builders.

2023-07-03 01:50 UTC, fa0311 requested changes
Does not work.

2023-07-03 22:46 UTC, nevkontakte commented
> Is this defined in the Swagger specification?

It is, with the change I'm proposing. Or is there an official Swagger specification for Twitter API that I'm not aware of?

> These identifier properties must allow null.

Why is that? AFAICT these properties (such as `__typename`) are meant to allow the clients to determine which union type is being provided in the response. If the property is null, how you the client determine which type it is dealing with?

For some of the types such properties were already indicated as required by your spec, so I assumed it was just an oversight that some others weren't. I experimented with querying these APIs and they seemed to always be not null in practice. Have you come across counter-examples where they were null?

> Also, in the case of openapi-generator, OneOf can be null-allowed.

Well, like I said, the fact that oapi-generator doesn't allow that is probably a bug (or a missing feature), but regardless of that, it seems like these properties _should_ be considered required for the Twitter's case.

> Does not work.

Could you elaborate? Seems to be working for me...

Apologies if I'm asking silly questions, I haven't dealt with Swagger before.

2023-07-04 00:41 UTC, fa0311 commented
> For some of the types such properties were already indicated as required by your spec, so I assumed it was just an oversight that some others weren't. I experimented with querying these APIs and they seemed to always be not null in practice. Have you come across counter-examples where they were null?

yes.
![image](https://github.com/fa0311/twitter-openapi/assets/34892635/65575e23-43b7-4049-b71c-ad8255dffd95)

I built `twitter_openapi_dart_generated` using `nevkontakte:main` and most test cases do not succeed.

```
DioException (DioException [unknown]: null

Error: Deserializing '[data, {home: {home_timeline_urt: {instructions: [{type: TimelineAddEntries, ...' to 'TimelineResponse' failed due to: Deserializing '[home, {home_timeline_urt: {instructions: [{type: TimelineAddEntries, entries...' to 'HomeTimelineResponseData' failed due to: Deserializing '[home_timeline_urt, {instructions: [{type: TimelineAddEntries, entries: [{ent...' to 'HomeTimelineHome' failed due to: Deserializing '[instructions, [{type: TimelineAddEntries, entries: [{entryId: tweet-16760190...' to 'Timeline' failed due to: Deserializing '[{type: TimelineAddEntries, entries: [{entryId: tweet-1676019064924430336, so...' to 'BuiltList<InstructionUnion>' failed due to: Deserializing '[type, TimelineAddEntries, entries, [{entryId: tweet-1676019064924430336, sor...' to 'InstructionUnion' failed due to: Deserializing '[type, TimelineAddEntries, entries, [{entryId: tweet-1676019064924430336, sor...' to 'TimelineAddEntries' failed due to: Deserializing '[{entryId: tweet-1676019064924430336, sortIndex: 1676026791606616064, content...' to 'BuiltList<TimelineAddEntry>' failed due to: Deserializing '[entryId, cursor-top-1676026791606616065, sortIndex, 1676026791606616065, con...' to 'TimelineAddEntry' failed due to: Deserializing '[entryType, TimelineTimelineCursor, __typename, TimelineTimelineCursor, value...' to 'ContentUnion' failed due to: Deserializing '[entryType, TimelineTimelineCursor, __typename, TimelineTimelineCursor, value...' to 'TimelineTimelineCursor' failed due to: Tried to construct class "TimelineTimelineCursor" with null for non-nullable field "itemType".)

```
I am maintaining `twitter_openapi_dart_generated` and cannot incorporate a modification that would destroy it.

> Why is that? AFAICT these properties (such as `__typename`) are meant to allow the clients to determine which union type is being provided in the response. If the property is null, how you the client determine which type it is dealing with?

In the case of TypeScript and Dart, the user must cast the type.

2023-07-06 21:56 UTC, nevkontakte commented
Well, I guess my assumption is wrong and one of your test cases has that field unset. Unfortunately, I don't know enough about your tests or where the test data came from to determine whether it is indeed my PR that's incorrect or something is not quite accurate with the test.

I withdraw this request. That said, thank you for all the work you've done, it helped my little project a lot.

2023-07-06 21:56 UTC, closed without merging

2023-07-06 22:20 UTC, fa0311 commented
Test cases can be found here. <https://github.com/fa0311/twitter_openapi_dart/blob/main/twitter_openapi_dart_generated/test/api_test.dart>

Dart is a null-safe statically typed language with strict type handling.
Nested tweets, such as replies, contain a `TimelineTimelineCursor`, but it does not have an `itemType`.